---
env: development
frontend:
  rootPath: "/app/"
api:
  prefix: api
  version: v1
  hostname: localhost
  port: 6543
  auth: authentications
  user: user
cookie:
  name: caliopen.web
  max-age: 3600
  signed: true
  secret: _4+%J;_F&?#!+mR&IsYq:Xg4A*wvse
seal:
  secret: D}(2$5q)#_#yKX90,+0d5?4**a6w
